### ISSUE TITLE
Currently have no clue why but ultracraft interferes with trinkets

### ISSUE THREAD

**Issue by walksanatora** [absolutelyaya/ultracraft#103]
it causes trinkets stuff to not realise it is in your slots when it is equipped
I have no clue why or what cold be causing this. but it is what happens.
examples: Plethora-fabric's neural-interface turns off after awhile
spectrum's items that apply effects constantly do not refresh
removing ultracraft (and changing nothing else) causes them to work

**Comment by walksanatora** [comment]
okay so it may be the fact that you are canceling inventory ticking
https://github.com/absolutelyaya/ultracraft/blob/fabric-1.20.1/src/main/java/absolutelyaya/ultracraft/mixin/PlayerInventoryMixin.java

**Comment by walksanatora** [comment]
why do you need to tick it uniquely???

**Comment by absolutelyaya** [comment]
> why do you need to tick it uniquely???

because the way that minecraft checks whether a slot is selected is faulty. If and only if your first hotbar slot is selected, your offhand counts as selected as well. Depending on which hotbar slot you have selected, it'll also tick the Xth main inventory slot as selected item.
This first off cannot be intentional, and second off, means that it doesn't work the way I need it to. The items are still all being ticked just like they would be otherwise, with only the `selected` argument being corrected.

It is a very invasive fix, but the mod isn't exactly designed for compatibility or modpacks, so I'm fine with occasional sacrifices like this

**Comment by walksanatora** [comment]
so what would happen if I disable this mixin

**Comment by walksanatora** [comment]
because I just tried to dual-wield weapons (one in first slot one in 2nd slot) and it worked perfectly fine (only mainhand shooting the gun)

**Comment by absolutelyaya** [comment]
well, I wrote this mixin 6 months ago so I can't fully remember what the issues were; pretty sure it had to do with weapons alt fire and offhand stuff.
Considering I specifically tick all non-weapon items without the fix, I don't see why other items would behave differently without the mixin

**Comment by walksanatora** [comment]
it is because trinkets (probally) mixins into the inventory tick method to tell it to tick trinkets alongside inventory
but since you cancel before trinkets gets it's chance (since they probally inject into TAIL) it never ticks them

**Comment by walksanatora** [comment]
infact it does https://github.com/emilyploszaj/trinkets/blob/main/src/main/java/dev/emi/trinkets/mixin/PlayerInventoryMixin.java

**Comment by absolutelyaya** [comment]
ugh that's annoying

**Comment by walksanatora** [comment]
also fabric discord has a idea for a mixin to change. a @ModifyArg mixin on the selected argument
and then just check stuff there

**Comment by walksanatora** [comment]
(to quote @Linguardium on discord)
> sound be simple enough to modify arg the inventoryTick and compare defaultedList to main

**Comment by absolutelyaya** [comment]
I don't really see how that'd work-
I'm not aware of a way to get the object a method is run on, so I can't compare instances. Using `ModifyArg` I have only access to the target arguments value, which I can't really do anything with. `ModifyArgs` at least would let me get the `slot` argument as well, but I still have no way of knowing what list it's iterating over, meaning worst case the item ticks 3 times instead of 1

**Comment by Noaaan** [comment]
> because the way that minecraft checks whether a slot is selected is faulty. If and only if your first hotbar slot is selected, your offhand counts as selected as well. Depending on which hotbar slot you have selected, it'll also tick the Xth main inventory slot as selected item.

Instead of checking selected slots - Can you not just check if your item is in the main hand of the entity, and then tick?

**Comment by absolutelyaya** [comment]
looking at it like that, I could actually drop the mixin alltogether and just do the check in the item itself; only problem with that is I'll need to call the check on every Weapon Item separately, which is kinda messy imo- but ah well

**Comment by Linguardium** [comment]
just as an exercise in learning:
```
   FRAME FULL [net/minecraft/entity/player/PlayerInventory java/util/Iterator net/minecraft/util/collection/DefaultedList I] [net/minecraft/item/ItemStack net/minecraft/world/World net/minecraft/entity/player/PlayerEntity I I]
    INVOKEVIRTUAL net/minecraft/item/ItemStack.inventoryTick (Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;IZ)V
```
the frame for the inventory tick call has the defaultedList variable in the LVT

https://github.com/LlamaLad7/MixinExtras/wiki/Local

the `@Local` annotation should let you capture locals, and if not in a ModifyArg, you could WrapOperation instead.

**Comment by absolutelyaya** [comment]
oh, I didn't even know MixinExtras is a thing. Thanks for telling me about it, the stuff it adds looks really useful
