### ISSUE TITLE
/fill and /setblock are not reset by checkpoints

### ISSUE THREAD

**Issue by ContagiousPow** [absolutelyaya/ultracraft#142]
basically what the title says, when using a command block to /fill something after the player goes through a checkpoint, the checkpoint does not reset it, unlike the other map blocks in the room. this is also true for things such as falling gravel or sand, which do not get reset either

**Comment by absolutelyaya** [comment]
yea, only mapping blocks get reset. that's why they exist
if you do stuff with command blocks, you gotta figure out resetting that yourself. 
I can't do much about falling blocks either; a workaround would be to have a dummy door listener that doesn't have a flag bound to it, has the reset block type as air and either the closed or open type as whatever the falling block is. then just have the area encompass where those blocks would be after falling
