### ISSUE TITLE
Firing guns and moving in high velocity mode renders across clients

### ISSUE THREAD

**Issue by FlyingFluffyWolf** [absolutelyaya/ultracraft#18]
When others fire weapons or dash/slide, the animations render across clients, so one person shooting a gun will play the animation for someone else in their hotbar/hand.

**Comment by absolutelyaya** [comment]
The weapon part usually happens when a Weapon is copied in creative via the middle mouse key. I _think_ it's a geckolib issue where the animation sync ID is copied along with all other item data; same for putting a weapon on pedestals in creative or any other action copying item stacks.
A way to prevent that is manually taking new weapons either from the creative inventory or /give

The Wings however are a networking bug that I'm already working on
