### ISSUE TITLE
Dashing and sliding are in the same button

### ISSUE THREAD

**Issue by DoomsdayDet06** [absolutelyaya/ultracraft#73]
I cant dash and slide differently because they are both mapped at crouch

**Comment by absolutelyaya** [comment]
When you enter high velocity mode, sprinting is replaced with sliding and crouching is replaced by dashing.
You switch between movement modes using a new Keybind (Default [V])

**Comment by DoomsdayDet06** [comment]
i use R for running, so when i bind crouch to shift so i can dash, both dash and slide bind to shift

**Comment by absolutelyaya** [comment]
I tried binding running to R and crouch to shift as you described, but can't recreate the issue; all I can think of as a potential cause is a mod conflict, since most of the custom movement doesn't really check for keybinds and instead just overrides sprint/crouch behavior. That, or a misunderstanding
