### ISSUE TITLE
Sky block /fill is kinda weird

### ISSUE THREAD

**Issue by GladiosAnimations** [absolutelyaya/ultracraft#90]
basically:
if i try to use a /fill command, and try to make the "type" NBT in to day, night evening, it doesn't work.
if I use /data  merge though, it works like a charm.

i know this isn't really a bug and a skill issue from my point, but how can I make a large area of skyblocks change its time?

**Comment by absolutelyaya** [comment]
since they're all technically the same block, minecraft thinks the block doesn't change so it ignores the block placements. It is janky, but I can't do much about it unfortunately.
A workaround is to replace skyblocks with a different block first (like for example bedrock or anything that doesn't appear in the build) and then immediately replace it again with the new type of sky block

https://github.com/absolutelyaya/ultracraft/assets/70072204/cd5986fe-fdb6-4d09-9a6c-c2fcc36e5af0
